package playground

import swiftvis2.plotting.renderer.SwingRenderer

object SwingPlotTesting extends App {
  import PlotTesting._
//  SwingRenderer(legendScatter(), makeMain = true)
//  SwingRenderer(barPlot())
//  SwingRenderer(performanceTest(), largeDim, largeDim, true)
//  SwingRenderer(scatter1(), medDim, medDim)
//  SwingRenderer(scatter2(), medDim, medDim)
//  SwingRenderer(scatterLines(), medDim, medDim)
   SwingRenderer(legendScatter(), medDim, medDim, true)
   SwingRenderer(legendScatterGrid(), medDim, medDim, true)

  // SwingRenderer(scatterWithErrorBars(), medDim, medDim)
  // SwingRenderer(scatterMultidata(), medDim, medDim)
  // SwingRenderer(scatterWithSizeandColor(), medDim, medDim)
  // SwingRenderer(scatterLogLog(), medDim, medDim)
  // SwingRenderer(fullScatter(), medDim, medDim)
  // SwingRenderer(stackedNNTest(), medDim, medDim)
  // SwingRenderer(gridNNTest(), medDim, medDim)
  // SwingRenderer(stackedCNTest(), medDim, medDim)
  // SwingRenderer(gridCNTest(), medDim, medDim)
  // SwingRenderer(barChart(), smallDim, 500)
  // SwingRenderer(histogram(), smallDim, smallDim)
  // SwingRenderer(histogramFromData(), smallDim, smallDim)
  // SwingRenderer(histogramSide(), smallDim, smallDim)
  // SwingRenderer(histogram2(), smallDim, smallDim)
  // SwingRenderer(histogramGrid(), medDim, medDim)
  // SwingRenderer(longForm(), 1200, 1000)
//  SwingRenderer(ringPlotGridBug(), 1200, 1000, true)
  // SwingRenderer(coloredSurfacePlot(), 1200, 1000, true)
  // SwingRenderer(boxPlot(), smallDim, smallDim)
  // SwingRenderer(violinPlot(), smallDim, smallDim)
  // val rowPlot = rowOfDists()
  // SwingRenderer(rowPlot, 1200, smallDim)
  // val colPlot = colOfDists()
  // SwingRenderer(colPlot, 1200, smallDim)
  // val ptPlot = pressureTempPlot()
  // SwingRenderer(ptPlot, smallDim, smallDim)
  // SwingRenderer(colorTest(), largeDim, largeDim)
  // SwingRenderer(simpleFull(), smallDim, smallDim)
  // SwingRenderer(gridSkipAxisLabels(), smallDim, smallDim, true)
//  SwingRenderer(buildUpFluent(), smallDim, smallDim, true)
}
